# Generated by Django 4.1.4 on 2023-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fakekartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banner'),
        ),
    ]
